# Generated by Django 5.2.7 on 2025-11-03 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_type', models.CharField(blank=True, max_length=50)),
                ('complexity', models.CharField(blank=True, max_length=50)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('isOpenForCollaboration', models.BooleanField(default=True)),
                ('seekingMentorship', models.BooleanField(default=False)),
                ('teamSize', models.PositiveIntegerField(default=2)),
                ('timeCommitment', models.CharField(blank=True, max_length=50)),
                ('crossInstitutional', models.BooleanField(default=False)),
                ('remoteCollaboration', models.BooleanField(default=True)),
                ('communicationTool', models.CharField(blank=True, max_length=100)),
                ('projectManagementTool', models.CharField(blank=True, max_length=100)),
                ('fileSharingTool', models.CharField(blank=True, max_length=255)),
                ('meetingFrequency', models.CharField(blank=True, max_length=50)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('repositoryName', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects', to=settings.AUTH_USER_MODEL)),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='users.skill')),
            ],
        ),
        migrations.CreateModel(
            name='TeamRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_requirements', to='projects.project')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('lead', 'Lead'), ('co-lead', 'Co-Lead'), ('contributor', 'Contributor'), ('mentor', 'Mentor')], default='contributor', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_joined', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
    ]
